[2025-04-12T10:18:36.868+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-12T10:18:36.902+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_ingestion_dag.ingest scheduled__2025-04-12T09:00:00+00:00 [queued]>
[2025-04-12T10:18:36.912+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_ingestion_dag.ingest scheduled__2025-04-12T09:00:00+00:00 [queued]>
[2025-04-12T10:18:36.914+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-12T10:18:36.935+0000] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): ingest> on 2025-04-12 09:00:00+00:00
[2025-04-12T10:18:36.939+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=209) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-12T10:18:36.943+0000] {standard_task_runner.py:72} INFO - Started process 220 to run task
[2025-04-12T10:18:36.966+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather_ingestion_dag', 'ingest', 'scheduled__2025-04-12T09:00:00+00:00', '--job-id', '771', '--raw', '--subdir', 'DAGS_FOLDER/weather_ingestion_dag.py', '--cfg-path', '/tmp/tmp66rtrdek']
[2025-04-12T10:18:36.983+0000] {standard_task_runner.py:105} INFO - Job 771: Subtask ingest
[2025-04-12T10:18:37.079+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_ingestion_dag.ingest scheduled__2025-04-12T09:00:00+00:00 [running]> on host e1fcb75fb946
[2025-04-12T10:18:37.209+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='beni' AIRFLOW_CTX_DAG_ID='weather_ingestion_dag' AIRFLOW_CTX_TASK_ID='ingest' AIRFLOW_CTX_EXECUTION_DATE='2025-04-12T09:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-12T09:00:00+00:00'
[2025-04-12T10:18:37.210+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-12T10:18:37.213+0000] {weather_ingestion_dag.py:31} INFO - üåç Current UTC hour: 2025-04-12T10:00:00+00:00
[2025-04-12T10:18:37.223+0000] {logging_mixin.py:190} INFO - ‚ùå API Error: HTTPSConnectionPool(host='api.brightsky.dev', port=443): Max retries exceeded with url: /weather?lat=49.89&lon=10.89&date=2025-04-12&tz=Etc%2FUTC (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff7404ef90>: Failed to resolve 'api.brightsky.dev' ([Errno -2] Name or service not known)"))
[2025-04-12T10:18:37.225+0000] {weather_ingestion_dag.py:38} INFO - ‚è± Found 0 matching entries for this hour
[2025-04-12T10:18:37.226+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-12T10:18:37.238+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-12T10:18:37.239+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=weather_ingestion_dag, task_id=ingest, run_id=scheduled__2025-04-12T09:00:00+00:00, execution_date=20250412T090000, start_date=20250412T101836, end_date=20250412T101837
[2025-04-12T10:18:37.291+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-12T10:18:37.304+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-12T10:18:37.305+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
