[2025-04-12T10:18:36.708+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-12T10:18:36.762+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_ingestion_dag.ingest scheduled__2025-04-11T19:00:00+00:00 [queued]>
[2025-04-12T10:18:36.771+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_ingestion_dag.ingest scheduled__2025-04-11T19:00:00+00:00 [queued]>
[2025-04-12T10:18:36.771+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-12T10:18:36.811+0000] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): ingest> on 2025-04-11 19:00:00+00:00
[2025-04-12T10:18:36.817+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=206) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-12T10:18:36.824+0000] {standard_task_runner.py:72} INFO - Started process 218 to run task
[2025-04-12T10:18:36.820+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather_ingestion_dag', 'ingest', 'scheduled__2025-04-11T19:00:00+00:00', '--job-id', '769', '--raw', '--subdir', 'DAGS_FOLDER/weather_ingestion_dag.py', '--cfg-path', '/tmp/tmpow40fg5c']
[2025-04-12T10:18:36.832+0000] {standard_task_runner.py:105} INFO - Job 769: Subtask ingest
[2025-04-12T10:18:36.987+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_ingestion_dag.ingest scheduled__2025-04-11T19:00:00+00:00 [running]> on host e1fcb75fb946
[2025-04-12T10:18:37.130+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='beni' AIRFLOW_CTX_DAG_ID='weather_ingestion_dag' AIRFLOW_CTX_TASK_ID='ingest' AIRFLOW_CTX_EXECUTION_DATE='2025-04-11T19:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-11T19:00:00+00:00'
[2025-04-12T10:18:37.134+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-12T10:18:37.137+0000] {weather_ingestion_dag.py:31} INFO - üåç Current UTC hour: 2025-04-12T10:00:00+00:00
[2025-04-12T10:18:37.149+0000] {logging_mixin.py:190} INFO - ‚ùå API Error: HTTPSConnectionPool(host='api.brightsky.dev', port=443): Max retries exceeded with url: /weather?lat=49.89&lon=10.89&date=2025-04-12&tz=Etc%2FUTC (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff74151220>: Failed to resolve 'api.brightsky.dev' ([Errno -2] Name or service not known)"))
[2025-04-12T10:18:37.150+0000] {weather_ingestion_dag.py:38} INFO - ‚è± Found 0 matching entries for this hour
[2025-04-12T10:18:37.150+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-12T10:18:37.166+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-12T10:18:37.167+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=weather_ingestion_dag, task_id=ingest, run_id=scheduled__2025-04-11T19:00:00+00:00, execution_date=20250411T190000, start_date=20250412T101836, end_date=20250412T101837
[2025-04-12T10:18:37.212+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-12T10:18:37.235+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-12T10:18:37.236+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
