[2025-04-04T18:47:29.434+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-04T18:47:29.446+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_ingestion_dag.ingest scheduled__2025-04-04T17:00:00+00:00 [queued]>
[2025-04-04T18:47:29.450+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_ingestion_dag.ingest scheduled__2025-04-04T17:00:00+00:00 [queued]>
[2025-04-04T18:47:29.451+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-04T18:47:29.456+0000] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): ingest> on 2025-04-04 17:00:00+00:00
[2025-04-04T18:47:29.460+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=106) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-04T18:47:29.462+0000] {standard_task_runner.py:72} INFO - Started process 108 to run task
[2025-04-04T18:47:29.462+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather_ingestion_dag', 'ingest', 'scheduled__2025-04-04T17:00:00+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/weather_ingestion_dag.py', '--cfg-path', '/tmp/tmpwfo1ifgl']
[2025-04-04T18:47:29.464+0000] {standard_task_runner.py:105} INFO - Job 39: Subtask ingest
[2025-04-04T18:47:29.502+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_ingestion_dag.ingest scheduled__2025-04-04T17:00:00+00:00 [running]> on host de9170386aa6
[2025-04-04T18:47:29.553+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='beni' AIRFLOW_CTX_DAG_ID='weather_ingestion_dag' AIRFLOW_CTX_TASK_ID='ingest' AIRFLOW_CTX_EXECUTION_DATE='2025-04-04T17:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-04T17:00:00+00:00'
[2025-04-04T18:47:29.554+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-04T18:47:37.566+0000] {logging_mixin.py:190} INFO - ‚ùå API Error: HTTPSConnectionPool(host='api.brightsky.dev', port=443): Max retries exceeded with url: /weather?lat=49.89&lon=10.89&date=2025-04-04&tz=Europe%2FBerlin (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffffad61c320>: Failed to resolve 'api.brightsky.dev' ([Errno -3] Temporary failure in name resolution)"))
[2025-04-04T18:47:37.567+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-04T18:47:37.589+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-04T18:47:37.590+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=weather_ingestion_dag, task_id=ingest, run_id=scheduled__2025-04-04T17:00:00+00:00, execution_date=20250404T170000, start_date=20250404T184729, end_date=20250404T184737
[2025-04-04T18:47:37.648+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-04T18:47:37.660+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-04T18:47:37.661+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
