[2025-04-05T00:58:52.057+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-05T00:58:52.074+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_ingestion_dag.ingest scheduled__2025-04-04T23:00:00+00:00 [queued]>
[2025-04-05T00:58:52.080+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_ingestion_dag.ingest scheduled__2025-04-04T23:00:00+00:00 [queued]>
[2025-04-05T00:58:52.081+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-05T00:58:52.091+0000] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): ingest> on 2025-04-04 23:00:00+00:00
[2025-04-05T00:58:52.104+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=168) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-05T00:58:52.106+0000] {standard_task_runner.py:72} INFO - Started process 179 to run task
[2025-04-05T00:58:52.106+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather_ingestion_dag', 'ingest', 'scheduled__2025-04-04T23:00:00+00:00', '--job-id', '63', '--raw', '--subdir', 'DAGS_FOLDER/weather_ingestion_dag.py', '--cfg-path', '/tmp/tmpo4r4esy1']
[2025-04-05T00:58:52.108+0000] {standard_task_runner.py:105} INFO - Job 63: Subtask ingest
[2025-04-05T00:58:52.163+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_ingestion_dag.ingest scheduled__2025-04-04T23:00:00+00:00 [running]> on host de9170386aa6
[2025-04-05T00:58:52.220+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='beni' AIRFLOW_CTX_DAG_ID='weather_ingestion_dag' AIRFLOW_CTX_TASK_ID='ingest' AIRFLOW_CTX_EXECUTION_DATE='2025-04-04T23:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-04T23:00:00+00:00'
[2025-04-05T00:58:52.222+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-05T00:59:07.298+0000] {logging_mixin.py:190} INFO - ‚ùå API Error: HTTPSConnectionPool(host='api.brightsky.dev', port=443): Max retries exceeded with url: /weather?lat=49.89&lon=10.89&date=2025-04-05&tz=Europe%2FBerlin (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1010)')))
[2025-04-05T00:59:07.299+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-05T00:59:07.312+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-05T00:59:07.312+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=weather_ingestion_dag, task_id=ingest, run_id=scheduled__2025-04-04T23:00:00+00:00, execution_date=20250404T230000, start_date=20250405T005852, end_date=20250405T005907
[2025-04-05T00:59:07.376+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-05T00:59:07.386+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-05T00:59:07.387+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
